### ISSUE TITLE
Request for Grade

### ISSUE THREAD

**Issue by MacKenzieRose** [MacKenzieRose/confectionery-website-prototype#6]
Hi @thomasjbradley,

For this website, I tried to incorporate the biggest takeaways from our first semester: commiting regularly and descriptively, flexbox, a variety of responsive links, responsive sections and typography, and the overall organization of coding files. With this in mind, I think what I'm submitting is worth an A-. 

From a coding standpoint, the site works, and incorporates some of the most important content we've covered; it also functions on mobile. It's built in a reasonably intuitive order, and my files are well-organized. That being said, it's not a particularly pretty site, and a few aspects (like the social media icons having links extend outside themselves) indicate how little time I really spent actually coding. Some of my fixes for issues found in-class today also added lines of code I could likely remove and simplify if I spent time doing so. Therefore, although it meets the basic requirements, I don't consider this an A+ project.

**Comment by MacKenzieRose** [comment]
@thomasjbradley As a follow-up, can I have a grade for browser testing?

Cheers!

MacKenzie

**Comment by thomasjbradley** [comment]
@MacKenzieRose Yep—I haven’t entered any of those yet. I’m still working my way through the final projects.

**Comment by MacKenzieRose** [comment]
@thomasjbradley 

Thanks so much! Sorry for being impatient XD
